package:
  name: ogre
  version: "1.10"

source:
  hg_url: /src/ogre/
  hg_tag: v1-10

build:
  number: 1

requirements:
  build:
    - python
    - boost
    - cmake
    - freeimage
    - freetype
    - pkgconfig
    - sdl

  run:
    - python
    - boost
    - freeimage
    - freetype
    - pkgconfig
    - sdl

about:
    home: http://ogre3d.org
    summary: >
      Anaconda package for Ogre3D.
    license: MIT
